production:
  use_s3: true
  s3_bucket: abc
  s3_access_key: akjaskj
  s3_secret: kjsdacnd

staging:
  use_s3: true
  s3_bucket: abc
  s3_access_key: akjaskj
  s3_secret: kjsdacnd

development:
  use_s3: true
  s3_bucket: abc
  s3_access_key: akjaskj
  s3_secret: kjsdacnd

